export const infoToShowInTable = {
    central: [
      { key: 'centralName', label: 'Central' },
      { key: 'codeName', label: 'Sitio' },
      { key: 'siteCode', label: 'Emplazamiento' },
      { key: 'description', label: 'Descripcion' },
      { key: 'provinceName', label: 'Provincia' },
      { key: 'districtName', label: 'Partido' },
      { key: 'localityName', label: 'localidad' },
      { key: 'address', label: 'Domicilio' },
      { key: 'latitude', label: 'Latitud' },
      { key: 'longitude', label: 'Longuitud' },
      { key: 'owner', label: 'Propietario' },
      { key: 'observations', label: 'Observaciones' },
      { key: 'status', label: 'Estado' },
      { key: 'createdAt', label: 'Creado' },
      { key: 'updatedAt', label: 'Modificado' },
    ],
    catalogSubrack: [
      { key: 'vendor', label: 'Vendor' },
      { key: 'partNumber', label: 'No. Parte' },
      { key: 'subrackType', label: 'Tipo' },
      { key: 'subrackFamily', label: 'Familia' },
      { key: 'modelName', label: 'Model' },
      { key: 'totalSlots', label: 'Cant. Slots' },
      { key: 'description', label: 'Descripcion' },
      { key: 'observations', label: 'Obs.' },
      { key: 'technology', label: 'Tecnologia' },
      { key: 'roadmap', label: 'ROADMAP' },
      { key: 'owner', label: 'Propietario' },
      { key: 'createdAt', label: 'Creado' },
      { key: 'updatedAt', label: 'Modificado' },
    ],
    catalogBoard: [
      { key: 'vendor', label: 'Vendor' },
      { key: 'boardName', label: 'Nombre' },
      { key: 'partNumber', label: 'No de Parte' },
      { key: 'description', label: 'Descripcion' },
      { key: 'observations', label: 'Obs.' },
      { key: 'slotSize', label: 'Cant. Slot Ocupa' },
      { key: 'roadmap', label: 'ROADMAP' },
      { key: 'createdAt', label: 'Creado' },
      { key: 'updatedAt', label: 'Modificado' },
    ],
    catalogTransceiver: [
      { key: 'vendor', label: 'Vendor' },
      { key: 'partNumber', label: 'No. Parte' },
      { key: 'modelName', label: 'Model' },
      { key: 'type', label: 'Tipo' },
      { key: 'technology', label: 'Tecnologia' },
      { key: 'description', label: 'Descripcion' },
      { key: 'observations', label: 'Obs.' },
      { key: 'roadmap', label: 'ROADMAP' },
      { key: 'createdAt', label: 'Creado' },
      { key: 'updatedAt', label: 'Modificado' },
    ],
    catalogSignal: [
      { key: 'type', label: 'Tipo' },
      { key: 'subType', label: 'SubTipo' },
      { key: 'amount', label: 'BW' },
      { key: 'unit', label: 'Unidad' },
      { key: 'observation', label: 'Observaciones' },
      { key: 'createdAt', label: 'Creado' },
      { key: 'updatedAt', label: 'Modificado' },
    ], 
    catalogVendor: [
      { key: 'vendorName', label: 'Vendor' },
      { key: 'country', label: 'Pais' },
      { key: 'observation', label: 'Observaciones' },
      { key: 'createdAt', label: 'Creado' },
      { key: 'updatedAt', label: 'Modificado' },
    ],
  } as const;